{% set name = "spyder-screencast" %}
{% set version = "0.0.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyder-screencast-{{ version }}.tar.gz
  sha256: 212f8750c54b19038380e71b22393f01705f3055909136bba9e02014ed12ff0b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - qscreencast
    - spyder >=5

test:
  imports:
    - spyder_screencast

about:
  home: https://github.com/Semi-ATE/spyder-screencast
  summary: screencaster for spyder 5.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
