{% set name = "spyder-screencast" %}
{% set version = "0.0.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyder-screencast-{{ version }}.tar.gz
  sha256: 7e815a21d858da53bcdf7e745063a0e57a023096cc2cc9b9e9d0ff6276cddad2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - qscreencast
    - spyder >=5

test:
  imports:
    - spyder_screencast

about:
  home: https://github.com/Semi-ATE/spyder-screencast
  summary: screencaster for spyder 5.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
